// Generated by CoffeeScript 1.4.0
(function() {
  var Apnshit, Notification, apnshit, devices, fs, key, value, _, _ref;

  _ref = require('../lib/apnshit/common');
  for (key in _ref) {
    value = _ref[key];
    eval("var " + key + " = value;");
  }

  console.log("asd");

  apnshit = require('../lib/apnshit');

  fs = require('fs');

  _ = require('underscore');

  Apnshit = apnshit.Apnshit;

  Notification = apnshit.Notification;

  devices = JSON.parse(fs.readFileSync('devices/devices.json'));

  console.log("devices: *", devices.length, "*");

}).call(this);
